/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parteGrafica;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import socket.Cliente;
import socket.Servidor;

/**
 *
 * @author annelis
 */
public class ClienterForm extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form ServidorForm
     */
    public ClienterForm() {
        initComponents();
       this.setLocationRelativeTo(null);
       
       this.getRootPane().setDefaultButton(this.AnalizarjButton);
       
       //para ejecutar con los sockets
       Servidor servidor = new Servidor(5000);
       servidor.addObserver(this);
       Thread hilo = new Thread(servidor);
       hilo.start();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbrirjButton = new javax.swing.JButton();
        GuardarjButton = new javax.swing.JButton();
        File1Button = new javax.swing.JButton();
        File2jButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AnalizarjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));

        AbrirjButton.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        AbrirjButton.setText("Abrir proyecto");
        AbrirjButton.setToolTipText("");

        GuardarjButton.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        GuardarjButton.setText("Guardar");
        GuardarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarjButtonActionPerformed(evt);
            }
        });

        File1Button.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        File1Button.setText("Choose File 1");
        File1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                File1ButtonActionPerformed(evt);
            }
        });

        File2jButton.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        File2jButton.setText("Choose File 2");
        File2jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                File2jButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel1.setText("Proyecto 1");

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel2.setText("Proyecto 2");

        AnalizarjButton.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        AnalizarjButton.setText("Analizar");
        AnalizarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalizarjButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AbrirjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(GuardarjButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(166, 166, 166))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(File1Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(File2jButton)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AnalizarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AbrirjButton)
                            .addComponent(GuardarjButton))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(File1Button)
                            .addComponent(File2jButton))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(AnalizarjButton)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void File1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_File1ButtonActionPerformed
        // abrir la ruta de proyectos
        JFileChooser abrir = new JFileChooser();
        
        //filtro para que solo acepte extensiones .java
        FileNameExtensionFilter filtroAceptado = new FileNameExtensionFilter(".java","java");
        //validamos el filtro
        abrir.setFileFilter(filtroAceptado);
        
        //se abre la ventana para seleccionar el archivo deseado
        int seleccion = abrir.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION){
        //seleccion del archivo
        File archivo = abrir.getSelectedFile();
        
        try (FileReader leer = new FileReader(archivo);){
            String cadena = "";
            int valor = leer.read();
            
            while(valor != -1){
                cadena = cadena+(char)valor;
                valor = leer.read();
            }
            //mostrando en el area correspondiente
            this.jTextArea1.setText(cadena);
        
        } catch(Exception e){
        }
                
        }
    }//GEN-LAST:event_File1ButtonActionPerformed

    private void AnalizarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalizarjButtonActionPerformed
        // configurar para que me abra la ventana de Cliente Cargado
        ClienteCargadoForm abrirVentana = new ClienteCargadoForm(); 
        abrirVentana.setVisible(true);
        
        this.dispose();
       
        
        //analisis de ambos text area si se ejecuta de manera correcta
        
                //si existe algun error se envia al servidor 
        //Cliente notificacion = new Cliente(6000, mensaje);
    }//GEN-LAST:event_AnalizarjButtonActionPerformed

    private void File2jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_File2jButtonActionPerformed
              // abrir la ruta de proyectos
        JFileChooser abrir = new JFileChooser();
        
        //filtro para que solo acepte extensiones .java
        FileNameExtensionFilter filtroAceptado = new FileNameExtensionFilter(".java","java");
        //validamos el filtro
        abrir.setFileFilter(filtroAceptado);
        
        //se abre la ventana para seleccionar el archivo deseado
        int seleccion = abrir.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION){
        //seleccion del archivo
        File archivo = abrir.getSelectedFile();
        
        try (FileReader leer = new FileReader(archivo);){
            String cadena = "";
            int valor = leer.read();
            
            while(valor != -1){
                cadena = cadena+(char)valor;
                valor = leer.read();
            }
            //mostrando en el area correspondiente
            this.jTextArea2.setText(cadena);
        
        }   catch (IOException ex) {
                Logger.getLogger(ClienterForm.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }
    }//GEN-LAST:event_File2jButtonActionPerformed

    private void GuardarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarjButtonActionPerformed
        // para guardar ambos archivos
         // abrir archivo o carpeta correspondiente
             JFileChooser abrir = new JFileChooser();
         
        //se abre la ventana para seleccionar el archivo deseado
        int seleccion = abrir.showOpenDialog(this);
              
        if(seleccion == JFileChooser.APPROVE_OPTION){
            
            File archivo = abrir.getSelectedFile();
           
              try (FileWriter escribir = new FileWriter(archivo);){
            //capturando lo que existe en el text area, por ahora se guardan los archivos juntos
            //por lo que en un mismo archivo van todas las clases unidas
        escribir.write(this.jTextArea1.getText()); 
        escribir.write(this.jTextArea2.getText()); 
        }   catch (IOException ex) {
                Logger.getLogger(ClienterForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_GuardarjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirjButton;
    private javax.swing.JButton AnalizarjButton;
    private javax.swing.JButton File1Button;
    private javax.swing.JButton File2jButton;
    private javax.swing.JButton GuardarjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
