
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETEABRE = 19;
  public static final int BREAKS = 37;
  public static final int CHART = 32;
  public static final int Y = 8;
  public static final int INTEGERA = 40;
  public static final int PARENTESISCIERRA = 16;
  public static final int FINALA = 26;
  public static final int ENTERO = 41;
  public static final int O = 9;
  public static final int PUBLICA = 23;
  public static final int PUNTOCOMA = 21;
  public static final int OBJECTT = 34;
  public static final int MENORIGUAL = 14;
  public static final int PARENTESISABRE = 15;
  public static final int IGUAL = 6;
  public static final int THISA = 27;
  public static final int PRIVATEA = 24;
  public static final int VOIDT = 35;
  public static final int ID = 39;
  public static final int MAYORIGUAL = 12;
  public static final int DECIMAL = 42;
  public static final int EOF = 0;
  public static final int RESTURNS = 38;
  public static final int LLAVEABRE = 17;
  public static final int error = 1;
  public static final int LLAVECIERRA = 18;
  public static final int CADENA = 43;
  public static final int MENOS = 3;
  public static final int DOUBLET = 33;
  public static final int MENOR = 13;
  public static final int INTT = 29;
  public static final int MAYOR = 11;
  public static final int NO = 10;
  public static final int PUNTO = 22;
  public static final int ESDISTINTO = 7;
  public static final int CORCHETECIERRA = 20;
  public static final int BOOLEANT = 30;
  public static final int PROTECTEDA = 25;
  public static final int CLASST = 36;
  public static final int IMPORTA = 28;
  public static final int DIVISION = 5;
  public static final int MULTIPLICACION = 4;
  public static final int MAS = 2;
  public static final int STRINGT = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVISION",
  "IGUAL",
  "ESDISTINTO",
  "Y",
  "O",
  "NO",
  "MAYOR",
  "MAYORIGUAL",
  "MENOR",
  "MENORIGUAL",
  "PARENTESISABRE",
  "PARENTESISCIERRA",
  "LLAVEABRE",
  "LLAVECIERRA",
  "CORCHETEABRE",
  "CORCHETECIERRA",
  "PUNTOCOMA",
  "PUNTO",
  "PUBLICA",
  "PRIVATEA",
  "PROTECTEDA",
  "FINALA",
  "THISA",
  "IMPORTA",
  "INTT",
  "BOOLEANT",
  "STRINGT",
  "CHART",
  "DOUBLET",
  "OBJECTT",
  "VOIDT",
  "CLASST",
  "BREAKS",
  "RESTURNS",
  "ID",
  "INTEGERA",
  "ENTERO",
  "DECIMAL",
  "CADENA"
  };

