
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETEABRE = 42;
  public static final int WHILECC = 20;
  public static final int PUBLICR = 2;
  public static final int Y = 31;
  public static final int PARENTESISCIERRA = 39;
  public static final int OBJECTTV = 16;
  public static final int ENTERO = 47;
  public static final int THISR = 6;
  public static final int PRIVATER = 3;
  public static final int O = 32;
  public static final int DOWHILECC = 21;
  public static final int BOOLEANTV = 12;
  public static final int DOUBLETV = 15;
  public static final int FORCC = 19;
  public static final int PUNTOCOMA = 44;
  public static final int IFCC = 17;
  public static final int MENORIGUAL = 37;
  public static final int ELSECC = 18;
  public static final int PARENTESISABRE = 38;
  public static final int IGUAL = 29;
  public static final int ID = 46;
  public static final int MAYORIGUAL = 35;
  public static final int DECIMAL = 48;
  public static final int EOF = 0;
  public static final int LLAVECIERRA = 41;
  public static final int LLAVEABRE = 40;
  public static final int error = 1;
  public static final int STRINGTV = 13;
  public static final int RETURNSA = 24;
  public static final int VOIDTV = 9;
  public static final int CADENA = 49;
  public static final int MENOS = 26;
  public static final int MENOR = 36;
  public static final int PROTECTEDR = 4;
  public static final int MAYOR = 34;
  public static final int IMPORTR = 7;
  public static final int NO = 33;
  public static final int PUNTO = 45;
  public static final int CHARTV = 14;
  public static final int CLASSTV = 10;
  public static final int ESDISTINTO = 30;
  public static final int CORCHETECIERRA = 43;
  public static final int BREAKSA = 23;
  public static final int INTEGERR = 8;
  public static final int DIVISION = 28;
  public static final int FINALR = 5;
  public static final int MULTIPLICACION = 27;
  public static final int MAS = 25;
  public static final int INTTV = 11;
  public static final int SWITCHCC = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLICR",
  "PRIVATER",
  "PROTECTEDR",
  "FINALR",
  "THISR",
  "IMPORTR",
  "INTEGERR",
  "VOIDTV",
  "CLASSTV",
  "INTTV",
  "BOOLEANTV",
  "STRINGTV",
  "CHARTV",
  "DOUBLETV",
  "OBJECTTV",
  "IFCC",
  "ELSECC",
  "FORCC",
  "WHILECC",
  "DOWHILECC",
  "SWITCHCC",
  "BREAKSA",
  "RETURNSA",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVISION",
  "IGUAL",
  "ESDISTINTO",
  "Y",
  "O",
  "NO",
  "MAYOR",
  "MAYORIGUAL",
  "MENOR",
  "MENORIGUAL",
  "PARENTESISABRE",
  "PARENTESISCIERRA",
  "LLAVEABRE",
  "LLAVECIERRA",
  "CORCHETEABRE",
  "CORCHETECIERRA",
  "PUNTOCOMA",
  "PUNTO",
  "ID",
  "ENTERO",
  "DECIMAL",
  "CADENA"
  };
}

